mutation LockPeriod ($opId: String, $periodId: String!, $unlock: Boolean!, $reason: String) {
  result: lockPeriod(
    opId: $opId,
    periodId: $periodId, 
    unlock: $unlock,
    reason: $reason
    ) {
    success
    opId
    duplicate
  }
}
