#import "./report-user-fragment.gql"

query ForecastPreload {
  approxCount: forecastedReportCount
  filterOptions: reportFilterOptions {
    projectNames
    parentProjectNames
    customerNames
    partnerNames
    employeeNames
  }
  users: users {
    ...ReportUserFragment
  }
}
