query ReportLinks {
  reportLinks(query: { published: true }) {
    name
    description
    iconName
    iconColor
    externalUrl
    linkRef
    createdAt
    updatedAt
    createdBy
    updatedBy
    published
    promoted
  }
}
