#import "./report-user-fragment.gql"

query ReportPreload($preset: String, $query: ReportsQuery) {
  approxCount: reportCount(preset: $preset, query: $query)
  filterOptions: reportFilterOptions {
    projectNames
    parentProjectNames
    customerNames
    partnerNames
    employeeNames
  }
  users: users {
    ...ReportUserFragment
  }
}
