import { Theme } from '@fluentui/react'

export default {
  palette: {
     themeDarker: '#dcdcdc',
     themeDark: '#dcdcdc',
     themeDarkAlt: '#dcdcdc',
     themePrimary: '#dcdcdc',
     themeSecondary: '#dcdcdc',
     themeTertiary: '#dcdcdc',
     themeLight: '#dcdcdc',
     themeLighter: '#dcdcdc',
     themeLighterAlt: '#dcdcdc',
     black: '#f8f8f8', // strongest color, very light in dark theme
     blackTranslucent40: '#dcdcdc',
     neutralDark: '#f4f4f4',
     neutralPrimary: '#c9d1d9', // main text color'
     neutralPrimaryAlt: '#dadada',
     neutralSecondary: '#c9d1d9',
     neutralSecondaryAlt: '#dcdcdc',
     neutralTertiary: '#c8c8c8',
     neutralTertiaryAlt: '#6d6d6d',
     neutralQuaternary: '#4f4f4f',
     neutralQuaternaryAlt: '#484848',
     neutralLight: '#3f3f3f',
     neutralLighter: '#252422', // timesheet border, hover color. same as background for now
     neutralLighterAlt: '#282828',
     accent: '#dcdcdc',
     white: '#252422', // This is the page background.
     whiteTranslucent40: '#dcdcdc',
     yellowDark: '#dcdcdc',
     yellow: '#dcdcdc',
     yellowLight: '#dcdcdc',
     orange: '#dcdcdc',
     orangeLight: '#dcdcdc',
     orangeLighter: '#dcdcdc',
     redDark: '#dcdcdc',
     red: '#dcdcdc',
     magentaDark: '#dcdcdc',
     magenta: 'magenta',
     magentaLight: '#dcdcdc',
     purpleDark: '#dcdcdc',
     purple: '#dcdcdc',
     purpleLight: '#dcdcdc',
     blueDark: '#dcdcdc',
     blueMid: '#dcdcdc',
     blue: 'blue',
     blueLight: '#dcdcdc',
     tealDark: '#dcdcdc',
     teal: 'teal',
     tealLight: '#dcdcdc',
     greenDark: '#dcdcdc',
     green: 'green',
     greenLight: '#dcdcdc',
  }
} as Theme
