// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'divider': string;
  'menu': string;
  'root': string;
  'toggle': string;
  'userDetail': string;
  'userEmail': string;
  'userName': string;
  'userSignOut': string;
}
export const cssExports: CssExports;
export default cssExports;
