// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'count': string;
  'icon': string;
  'notification': string;
  'panel': string;
  'root': string;
  'toggle': string;
}
export const cssExports: CssExports;
export default cssExports;
