mutation($userId: String!, $configuration: UserConfigurationInput!) {
  result: addOrUpdateUserConfiguration(userId: $userId, configuration: $configuration) {
    success
    error {
      message
    }
  }
}
