import { loadTheme } from 'office-ui-fabric-react/lib/Styling'

const themes = {
    dark: {
        themePrimary: '#cf5f00',
        themeLighterAlt: '#080400',
        themeLighter: '#210f00',
        themeLight: '#3e1d00',
        themeTertiary: '#7c3a00',
        themeSecondary: '#b65500',
        themeDarkAlt: '#d36e15',
        themeDark: '#da8234',
        themeDarker: '#e4a064',
        neutralLighterAlt: '#000000',
        neutralLighter: '#000000',
        neutralLight: '#000000',
        neutralQuaternaryAlt: '#000000',
        neutralQuaternary: '#000000',
        neutralTertiaryAlt: '#000000',
        neutralTertiary: '#f6f6f6',
        neutralSecondary: '#f8f8f8',
        neutralPrimaryAlt: '#f9f9f9',
        neutralPrimary: '#f1f1f1',
        neutralDark: '#fcfcfc',
        black: '#fdfdfd',
        white: '#181c1f',
    },
    light: {
        themePrimary: '#cf5f00',
        themeLighterAlt: '#fdf8f3',
        themeLighter: '#f7e2d0',
        themeLight: '#f0caa8',
        themeTertiary: '#e29a5a',
        themeSecondary: '#d47119',
        themeDarkAlt: '#ba5700',
        themeDark: '#9d4900',
        themeDarker: '#743600',
        neutralLighterAlt: '#f6f6f6',
        neutralLighter: '#f2f2f2',
        neutralLight: '#e8e8e8',
        neutralQuaternaryAlt: '#d8d8d8',
        neutralQuaternary: '#cecece',
        neutralTertiaryAlt: '#c6c6c6',
        neutralTertiary: '#a5adb3',
        neutralSecondary: '#8a939a',
        neutralPrimaryAlt: '#717a81',
        neutralPrimary: '#181c1f',
        neutralDark: '#424a50',
        black: '#252422',
        white: '#fdfdfd',
    }
}

export default (themeName) => loadTheme({ palette: themes[themeName] })