// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'buttonContainer': string;
  'label': string;
  'root': string;
  'row': string;
  'summary': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
