// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'buttonContainer': string;
  'root': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
