mutation SetTimesheetEventIgnored ($opId: String, $input: TimesheetIgnoreEventInput!) {
  result: setTimesheetEventIgnored(opId: $opId, input: $input) {
    success
    opId
    duplicate
    error {
      message
    }
  }
}
