mutation SubmitPeriod ($opId: String, $period: TimesheetPeriodInput!, $options: TimesheetOptions!) {
  result: submitPeriod(opId: $opId, period: $period, options: $options) {
    success
    opId
    duplicate
    error {
      message
    }
  }
}
