#import "../../../../graphql/fragments/timeentry-fragment.gql"

query LastMonthReport($userQuery: UserQuery) {
  timeEntries: forecastedReport {
    ...TimeEntryFragment
  }
  users: users(query: $userQuery) {
    id
    displayName
    mail
    photo {
      base64
    }
  }
}
