// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'buttonContainer': string;
  'colLeft': string;
  'colRight': string;
  'customer': string;
  'description': string;
  'labels': string;
  'name': string;
  'root': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
