// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'isSelected': string;
  'root': string;
  'suggestionIcon': string;
  'suggestionValue': string;
}
export const cssExports: CssExports;
export default cssExports;
