name: Build and deploy container app to Azure Web App - didapp-docker-630

on:
  push:
    branches:
      - feature/docker-publish

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/did:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/did:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp-docker-630'
        slot-name: 'production'
        publish-profile: ${{ secrets.DIDAPP_DOCKER_PUBLISH_PROFILE }}
        images: '${{ secrets.DOCKER_USERNAME }}/did:latest'