name: Build and deploy container app to Azure Web App - didapp-docker-630

on:
  push:
    branches:
      - feature/docker-publish

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - run: |
        docker build . -t did:${{ github.sha }}
        docker push did:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp-docker-630'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8a11f7bedec54385bd1d609774b3ff03 }}
        images: 'did:${{ github.sha }}'