name: Build and deploy to didapp

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/on_push_main_deploy.yml'
      - 'server/**'
      - 'client/**'
      - 'shared/**'
      - 'webpack/**'
      - 'package.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
    - uses: actions/checkout@master
    
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm packages
      run: |
        npm install --production --no-progress --loglevel silent --no-shrinkwrap --no-fund

    - name: Create package
      run: |
        npm run package
      env:
        NODE_ENV: production

    - uses: actions/upload-artifact@v2
      with:
        name: did-package
        path: ./did-package.zip

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp'
        publish-profile: ${{ secrets.DIDAPP_PUBLISH_PROFILE }}
        package: ./did-package.zip
