name: Build and deploy to didapp/feat

on:
  push:
    branches:
      - feat/*
    paths:
      - '.github/workflows/on_push_feat_deploy.yml'
      - 'server/**'
      - 'client/**'
      - 'shared/**'
      - 'webpack/**'
      - 'package.json'

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.18.1]

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        npm ci --no-audit --no-fund --loglevel=error

    - name: Create package
      run: |
        npm run package
      env:
        NODE_ENV: production

    - uses: actions/upload-artifact@v3
      with:
        name: did-package
        path: ./did-package.zip

    - name: 'Deploy package to didapp/feat'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp'
        slot-name: 'feat'
        publish-profile: ${{ secrets.DIDAPP_FEAT_PUBLISH_PROFILE }}
        package: ./did-package.zip
