name: Build and deploy to didapp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18.3]

    steps:
    - uses: actions/checkout@master
    
    - name: Select node version 12.8.3
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build and package
      run: |
        npm install
        npm run package:client
        npm run build:server

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'didapp'
        publish-profile: ${{ secrets.DIDAPP_PUBLISH_PROFILE }}
        package: .
