name: Package install and front-end build
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm packages
        run: |
          npm install --no-progress --loglevel silent --no-shrinkwrap --no-fund
      - name: Tests
        run: |
          npm run tests
        env:
          NODE_ENV: production
          TESTS_AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=https;AccountName=didsubstoragedev;AccountKey=EIfeW2mbJM56OMbFF3dR6YAXhdOQE2/n+DoFuxKkmgptmSqJ8aoJlgyOidkNtwIaQgB+DAd2+ALrGEGxeq6gHg==;EndpointSuffix=core.windows.net
